apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vjservice-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vjservice-pod
    spec:
      containers:
       - name: vjservice-container
         image: vdonthireddy/serviceinaks:1.0
         ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vjservice-service
  labels:
    app: vjservice-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vjservice-pod